ALTER TABLE "Photo"
ADD COLUMN "title" TEXT NOT NULL DEFAULT '',
ADD COLUMN "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN "deletedAt" TIMESTAMP;

ALTER TABLE "Video"
ADD COLUMN "title" TEXT NOT NULL DEFAULT '',
ADD COLUMN "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN "deletedAt" TIMESTAMP;


